apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rnm-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rnm-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # target 50% of requested CPU (100m -> target ~50m)
