apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnm-api
  labels:
    app: rnm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rnm-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rnm-api
    spec:
      containers:
        - name: rnm-api
          image: rnm-api:latest         # built inside Minikube's Docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:               # app is ready to receive traffic?
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:                # restart if unhealthy
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

